# ANN

### 라이브러리 불러오기

In [26]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [27]:
tf.__version__

'2.12.0'

## 1. 데이터 전처리

### 데이터 전처리

In [28]:
dataset= pd.read_csv('Dataset/Churn_modelling.csv')
X= dataset.iloc[:, 3:-1].values # 전체 행에서 3번째 열부터 마지막의 이전 열까지
y= dataset.iloc[:, -1].values # 전체 행에서 마지막 열

In [29]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [30]:
print(y)

[1 0 1 ... 1 1 0]


### 카테고리 데이터 인코딩(숫자형태로 바꾼다)

성별Gender 열을 라벨 인코딩 LabelEncoder()를 해준다.

LabelEncoder: 범주형 변수를 바꿔주는 것(Female: 0, male: 1)

In [31]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
X[:, 2]= le.fit_transform(X[:, 2])

In [32]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Geography(나라이름) 열을 원핫 인코딩 해준다.

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# ColumnTransformer: 여러 열의 데이터를 각각 다른 변환기로 처리하여 새로운 데이터셋을 생성한다.
ct= ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])], remainder= 'passthrough')
X= np.array(ct.fit_transform(X))
# ('encoder', OneHotEncoder(), 인코딩할 열 이름)
# remainder= 'passthrough': 설정한 열을 제외한 열은 그냥 통과한다.

In [34]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### train, test set으로 분리

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y , test_size= 0.2, random_state= 0)

### 특성 스케일링(범위 조정)

In [36]:
from sklearn.preprocessing import StandardScaler
# StandardScaler: 평균이 0, 분산이 1이 되도록 변환해 준다.
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

# 2. ANN 만들기 

### ANN 초기화 

In [37]:
ann= tf.keras.models.Sequential()

### ann에 입력층과 은닉층 추가하기

In [ ]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

### 은닉층 추가하기

In [38]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

### 출력층 추가하기

In [40]:
ann.add(tf.keras.layers.Dense(units= 1, activation= 'sigmoid'))

# 3. ann 학습 하기

### ann 컴파일(ann을 학습 시키기 저에 모델을 실행할 수 있는 형태로 변환하는 과정)

In [41]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

### ann train set 학습시키기

In [42]:
ann.fit(X_train, y_train, batch_size= 32, epochs= 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7441
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4564 - accuracy: 0.8045
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4384 - accuracy: 0.8105
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4301 - accuracy: 0.8140
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4242 - accuracy: 0.8159
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4195 - accuracy: 0.8188
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4148 - accuracy: 0.8214
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4104 - accuracy: 0.8245
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4062 - accuracy: 0.8260
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4026 - accura

# 4. 예측하고 평가하기

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card?: Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

으로 해본다.

In [43]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,50000]]))> 0.5)
# 0.5 보다 크면 1, 아니면 0

1/1 [==============================] - 0s 99ms/step
[[False]]


### test 예측하기

In [46]:
y_pred= ann.predict(X_test)
y_pred= (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### confusion matrix 로 확인하기

In [48]:
print(len(y_test))

2000


In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1506   89]
 [ 197  208]]


0.857